services:

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: arapp
      POSTGRES_USER: inzynier
      POSTGRES_PASSWORD: haslo
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inzynier -d arapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
